import Foundation
import GRDB
import Testing

@testable import PrudenceStore

/// The fixture is a real store: `tests/conftest.py`'s synthetic machine, ingested by the
/// engine itself and then `VACUUM INTO`'d, so the views under test are the views the engine
/// writes rather than SQL retyped here. It is regenerated by running the Python side, never
/// edited by hand.
enum Fixture {
    static var url: URL {
        guard let url = Bundle.module.url(forResource: "Fixtures/store", withExtension: "db") else {
            fatalError("the fixture store is missing from the test bundle")
        }
        return url
    }

    static func store() throws -> Store { try Store(url: url) }
}

@Suite("The contract")
struct ContractTests {

    @Test("A store at contract 1 opens")
    func opensAtOne() throws {
        let store = try Store(url: Fixture.url, expectedContractVersion: "1")
        #expect(try store.status()?.appContractVersion == "1")
    }

    @Test("A store the app does not know is refused, and both versions travel with the refusal")
    func refusesTwo() throws {
        #expect(throws: StoreError.contractMismatch(found: "1", expected: "2")) {
            _ = try Store(url: Fixture.url, expectedContractVersion: "2")
        }
    }

    @Test("The refusal says which side to update")
    func saysWhichSide() {
        let appIsOld = StoreError.contractMismatch(found: "2", expected: "1")
        #expect(appIsOld.message.contains("newer than this app"))
        let engineIsOld = StoreError.contractMismatch(found: "1", expected: "2")
        #expect(engineIsOld.message.contains("newer than the Prudence engine"))
        let ancient = StoreError.contractMismatch(found: nil, expected: "1")
        #expect(ancient.message.contains("prudence ingest"))
    }

    @Test("A missing database is a sentence, not a crash")
    func missingDatabase() {
        let path = "/nowhere/prudence.db"
        #expect(throws: StoreError.databaseMissing(path: path)) {
            _ = try Store(url: URL(fileURLWithPath: path))
        }
    }

    /// The case that broke the first build of this app against a real store: the engine had
    /// closed cleanly, so `prudence.db-wal` and `prudence.db-shm` were gone, and a connection
    /// opened `SQLITE_OPEN_READONLY` cannot create the wal-index it needs to read a WAL
    /// database. A healthy store nobody is writing to must still open.
    @Test("A WAL store with no side files open still opens, and still refuses writes")
    func walStoreWithoutSideFiles() throws {
        let directory = URL(fileURLWithPath: NSTemporaryDirectory())
            .appendingPathComponent("prudence-wal-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: directory) }

        let copy = directory.appendingPathComponent("prudence.db")
        try FileManager.default.copyItem(at: Fixture.url, to: copy)
        // Put it into WAL mode and close cleanly, which removes -wal and -shm.
        let writer = try DatabaseQueue(path: copy.path)
        try writer.inDatabase { try $0.execute(sql: "PRAGMA journal_mode = WAL") }
        try writer.close()
        #expect(
            FileManager.default.fileExists(atPath: copy.path + "-shm") == false,
            "the interesting case is precisely when the wal-index is gone")

        let store = try Store(url: copy)
        #expect(try store.status()?.sessions == 4)
        #expect(throws: DatabaseError.self) {
            try store.writeAttemptForTesting()
        }
    }

    @Test("Every view answers with exactly the columns APP_VIEWS names, in order")
    func columnsMatch() throws {
        let store = try Fixture.store()
        for view in Contract.View.allCases {
            #expect(try store.columns(of: view) == view.columns, "\(view.rawValue)")
        }
    }
}

@Suite("Row decoding")
struct RowTests {

    @Test("app_status is one row with the versions behind it")
    func status() throws {
        let row = try #require(try Fixture.store().status())
        #expect(!row.engineVersion.isEmpty)
        #expect(row.appContractVersion == "1")
        #expect(row.sessions == 4)
        #expect(row.projects == 1)
        #expect(row.lastIngestAt != nil)
        #expect((row.parserVersion ?? 0) >= 1)
    }

    @Test("app_usage_by_purpose_day decodes a day, a purpose and its tokens")
    func usage() throws {
        let rows = try Fixture.store().usageByPurposeDay(since: "2026-09-01")
        #expect(rows.count >= 3)
        let development = try #require(rows.first { $0.purpose == "development" })
        #expect(development.day == "2026-09-15")
        #expect(development.totalTokens == 5080)
        #expect(development.sessions >= 1)
        #expect(development.activeMinutes != nil)
    }

    @Test("app_session_list decodes a session with its purpose and its commits")
    func sessions() throws {
        let rows = try Fixture.store().sessions(
            startedBetween: "2026-09-01T00:00:00", and: "2026-10-01T00:00:00")
        #expect(rows.count == 4)
        let committed = try #require(rows.first { $0.countedCommits > 0 })
        #expect(committed.project.isEmpty == false)
        #expect(committed.sittings >= 1)
        #expect(committed.contentArchived == 1)
    }

    @Test("app_observation decodes both sides of a split and its coverage")
    func observations() throws {
        let rows = try Fixture.store().observations()
        #expect(rows.count == 3)
        // The engine's own order: a project's own rows first, the pooled ones last.
        #expect(rows.last?.isPooled == true)
        let first = try #require(rows.first)
        #expect(first.withN > 0 && first.withoutN > 0)
        #expect(first.coverage != nil)
        #expect(first.factVersion >= 1)
    }

    @Test("app_outcomes_by_week decodes, even with nothing measured yet")
    func outcomes() throws {
        let rows = try Fixture.store().outcomesByWeek()
        for row in rows { #expect(row.commits >= 0) }
    }

    @Test("The newest review row comes back as a headline")
    func review() throws {
        let row = try #require(try Fixture.store().latestReview())
        #expect(row.id == 1)
        #expect(row.rangeStart.hasPrefix("2026-09-08"))
        #expect(row.sections.contains("What you did"))
    }
}

@Suite("Where the store is")
struct StoreLocationTests {

    let home = URL(fileURLWithPath: "/Users/someone")

    @Test("PRUDENCE_DATA_DIR wins, so the app can be pointed at a copy")
    func environmentWins() {
        let located = StoreLocation.locate(
            settingsOverride: "/elsewhere/other.db",
            environment: ["PRUDENCE_DATA_DIR": "/copy"],
            home: home
        )
        #expect(located.url.path == "/copy/prudence.db")
        #expect(located.source == .environment)
    }

    @Test("Then the Settings override, expanded")
    func settingsNext() {
        let located = StoreLocation.locate(
            settingsOverride: "~/elsewhere/other.db", environment: [:], home: home)
        #expect(located.url.path == "/Users/someone/elsewhere/other.db")
        #expect(located.source == .settings)
    }

    @Test("Then the standard location paths.py returns on macOS")
    func standardLast() {
        let located = StoreLocation.locate(environment: [:], home: home)
        #expect(
            located.url.path == "/Users/someone/Library/Application Support/prudence/prudence.db")
        #expect(located.source == .standard)
    }

    @Test("An empty override is not an override")
    func emptyIgnored() {
        let located = StoreLocation.locate(
            settingsOverride: "  ", environment: ["PRUDENCE_DATA_DIR": ""], home: home)
        #expect(located.source == .standard)
    }
}
