/* Generated by build_standalone.py from assets/brand. Do not edit: rerun the script.

   The mark and the menu-bar glyph are carried as markup rather than as file
   references, so that a single-file copy stays self-contained. The fill is
   `currentColor`, which is how a surface picks `logo.svg` or `logo-white.svg`: it sets
   `--brand-ink` to that file's own ink. */

(function (global) {
  "use strict";

  var MARK_VIEWBOX = "58.094 116.072 397.052 279.857";
  var MARK_INNER = "<g transform=\"translate(280.75668274 116.07172163) scale(0.93701972)\"><path fill=\"currentColor\" d=\"M -79.17169873 0 H 0 L -110.41533744 266.56620515 A 52 52 0 0 1 -158.45707313 298.66666667 H -237.62877186 L -127.21343442 32.10046152 A 52 52 0 0 1 -79.17169873 0 Z\"/><path fill=\"currentColor\" d=\"M 21.64784401 0 H 106.36428856 C 124.89360649 0 141.46021489 4.59718781 154.57948029 13.37958178 C 167.69874569 22.16197575 176.96076268 34.85517401 181.53550619 50.32166269 C 186.11024969 65.78815138 185.85478396 83.54468714 180.7920028 102 H 107.23932466 C 59.96845518 102 21.64784401 56.33304448 21.64784401 0 Z\"/><path fill=\"currentColor\" d=\"M -28.8862106 122 H 173.51259811 C 165.14101018 140.45531286 152.47077495 158.21184862 136.63734843 173.67833731 C 120.8039219 189.14482599 102.30201223 201.83802425 82.78968685 210.62041822 C 63.27736146 219.40281219 43.36427402 224 24.83495608 224 H -71.13599397 Z\"/></g>";
  var GLYPH_VIEWBOX = "0 0 16 16";
  var GLYPH_INNER = "<g fill=\"currentColor\" transform=\"translate(-1.054796 -1.054794) scale(0.03537029)\"><g transform=\"translate(280.75668274 116.07172163) scale(0.93701972)\"><path d=\"M -79.17169873 0 H 0 L -110.41533744 266.56620515 A 52 52 0 0 1 -158.45707313 298.66666667 H -237.62877186 L -127.21343442 32.10046152 A 52 52 0 0 1 -79.17169873 0 Z\"/><path d=\"M 21.64784401 0 H 106.36428856 C 124.89360649 0 141.46021489 4.59718781 154.57948029 13.37958178 C 167.69874569 22.16197575 176.96076268 34.85517401 181.53550619 50.32166269 C 186.11024969 65.78815138 185.85478396 83.54468714 180.7920028 102 H 107.23932466 C 59.96845518 102 21.64784401 56.33304448 21.64784401 0 Z\"/><path d=\"M 107.23932466 102 H 173.51259811 V 122 H 107.23932466 Z\"/><path d=\"M -28.8862106 122 H 173.51259811 C 165.14101018 140.45531286 152.47077495 158.21184862 136.63734843 173.67833731 C 120.8039219 189.14482599 102.30201223 201.83802425 82.78968685 210.62041822 C 63.27736146 219.40281219 43.36427402 224 24.83495608 224 H -71.13599397 Z\"/></g></g>";
  var NS = "http://www.w3.org/2000/svg";
  var ASPECT = 1.418769;

  function svg(viewBox, inner, height, label) {
    var node = document.createElementNS(NS, "svg");
    node.setAttribute("viewBox", viewBox);
    node.setAttribute("role", "img");
    node.setAttribute("aria-label", label || "Prudence");
    node.setAttribute("height", String(height));
    node.style.height = height + "px";
    node.style.width = "auto";
    node.style.display = "block";
    node.innerHTML = inner;
    return node;
  }

  global.Brand = {
    ASPECT: ASPECT,
    /* The mark, cropped to its own bounding box, at a given height in px. */
    mark: function (height) {
      return svg(MARK_VIEWBOX, MARK_INNER, height || 18);
    },
    /* The menu-bar template glyph, square, 16 by 16 with 1 px optical padding. */
    glyph: function (size) {
      return svg(GLYPH_VIEWBOX, GLYPH_INNER, size || 16);
    }
  };
})(window);
